name: Inventory Drop Chance
author: Staartvin
website: http://dev.bukkit.org/server-mods/inventory-drop-chance/
main: Staartvin.InventoryDropChance.InventoryDropChance
version: 1.0
description: Control the dropping items on death
permissions:
      idc.keepallitems:
        description: A player with this permission will not lose any items.
        default: op
      idc.percentageloss:
        description: A player with this permission will lose items based on percentage.
        default: true
      idc.keepxp:
        description: A player with this permission will not lose any xp.
        default: false
commands: