name: Inventory Drop Chance
author: Staartvin
website: http://dev.bukkit.org/server-mods/inventory-drop-chance/
main: Staartvin.InventoryDropChance.InventoryDropChance
version: 1.4
description: Control the dropped items or dropped xp on death
softdepend: [WorldGuard, WGCustomFlags]
permissions:
      idc.keepallitems:
        description: A player with this permission will not lose any items.
        default: op
      idc.keepxp:
        description: A player with this permission will not lose any xp.
        default: false
commands: